services:
  streamlit_app:
    build: ./streamlit-app
    container_name: streamlit_app
    restart: unless-stopped
    ports:
      - "8501:8501" 
    volumes:
      - ./streamlit-app:/app
      - ./streamlit-app/secrets.toml:/root/.streamlit/secrets.toml 
    networks:
      - chirpstack-net

  nginx-proxy:
    image: nginx:stable
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - chirpstack-net

networks:
  chirpstack-net:
    external: true
