global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'snmp-gateway'
    static_configs:
      - targets: ['192.168.10.2']
    metrics_path: /snmp
    params:
      module: [tektelic_gateway]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
