{
 "title": "LoRaWAN",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "email",
    "label": "email",
    "query": "SELECT DISTINCT user_email FROM api_logs ORDER BY user_email\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, user_email, connexion_at, ip_address, endpoint\r\nFROM api_logs\r\nWHERE (\r\n  '${email:csv}' = 'All' OR user_email = ANY(string_to_array('${email:csv}', ','))\r\n)\r\nORDER BY connexion_at DESC\r\nLIMIT 20;\r\n"
    }
   ]
  },
  {
   "title": "Number of user",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT user_email) FROM api_logs;\r\n"
    }
   ]
  },
  {
   "title": "Status Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(*) FROM api_logs GROUP BY status;\r\n\r\n"
    }
   ]
  }
 ]
}