SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_LOGIN = "tomastenger@gmail.com"
SMTP_PASSWORD = "dror oqda ortw ndkv"
CHIRPSTACK_API_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjE0NDQzZWU3LWUyZWEtNDYzMC1hZjQ5LTkyZmIxNjljMjgyMCIsInR5cCI6ImtleSJ9.hWT8wdUejuXfMBdAO5128oLVT8k5dS0LKguhhGs_wxc"
